In [1]:
import json
import random
import pandas as pd

# 1.处理inter

In [2]:
name = "yelp"

inter_path = f"../../resource/{name}/{name}.inter"
user_path = f"../../resource/{name}/{name}.user"
item_path = f"../../resource/{name}/{name}.item"

w_pt_path = f"../../llm/{name}/{name}_pt.json"
w_ft_path = f"../../llm/{name}/{name}_ft.json"
w_pd_path = f"../../llm/{name}/{name}_pd.json"

In [3]:
# 读数据
inter_data = pd.read_csv(inter_path, sep="\t").sort_values(by=['user_id:token','rating:float', 'timestamp:float'])
user_data = pd.read_csv(user_path, sep="\t").sort_values(by=['user_id:token'])
item_data = pd.read_csv(item_path, sep="\t").sort_values(by=['item_id:token'])
#inter_data,user_data,item_data

In [4]:
# mini_user_data = user_data[:2000].reset_index(drop=True).reset_index().rename(columns={'index': 'id'})
# mini_user_data

In [5]:
# mini_item_data = item_data[:2000].reset_index(drop=True).reset_index().rename(columns={'index': 'item_id'})
# mini_item_data

In [6]:
# 分组&聚合
data_u = inter_data.groupby(['user_id:token']).count()
data_u["count"] = data_u["item_id:token"]
# 筛选=>10 core
data_u = data_u[data_u["count"] >= 50]
data_u

,item_id:token,rating:float,timestamp:float,useful:float,funny:float,cool:float,review_id:token,count
user_id:token,,,,,,,,
--Vu3Gux9nPnLcG9yO_HxA,52,52,52,52,52,52,52,52
--_H9j6ggxvqhh9nPofZwg,58,58,58,58,58,58,58,58
--_r6E98SNIrGU7weyNxbw,61,61,61,61,61,61,61,61
--u09WAjW741FdfkJXxNmg,95,95,95,95,95,95,95,95
-0YrXUvXz8112yHap35V2g,57,57,57,57,57,57,57,57
...,...,...,...,...,...,...,...,...
zy0el7c-IO4BvjxUgj-ZSw,88,88,88,88,88,88,88,88
zyNrXvJyYdC34tS6BcCykA,119,119,119,119,119,119,119,119
zyvxtbh5eJ86bVgk52Yflg,307,307,307,307,307,307,307,307
zz9wGVLClSDHoklHoj2g8w,57,57,57,57,57,57,57,57
zziJLt25YU6dp01sewR-IQ,62,62,62,62,62,62,62,62

In [7]:
# 按user_id筛选
mini_inter_data = inter_data[inter_data["user_id:token"].isin(data_u.index)]
mini_inter_data

,user_id:token,item_id:token,rating:float,timestamp:float,useful:float,funny:float,cool:float,review_id:token
5262245,--Vu3Gux9nPnLcG9yO_HxA,eGK4SEZakzmUzIKBfo_b2Q,1.0,1462312094,0,0,0,Xp3JUqi_ztPPcE47TWQlCQ
1642567,--Vu3Gux9nPnLcG9yO_HxA,j_AhCyEzJpo3sS7NZRFKQA,1.0,1493208089,1,1,1,wYttdXhyLXZkt98UiIGScA
4255703,--Vu3Gux9nPnLcG9yO_HxA,_GGq0vYmwMP5gk-81m5OVg,1.0,1499614772,0,0,1,LoMjmjzKP99CGXS2CIimtQ
1919366,--Vu3Gux9nPnLcG9yO_HxA,UNkOa6syMXonsoTErl2BIg,1.0,1502627982,2,0,0,RUkY2wCbepFC-sOTcNNqHA
6971731,--Vu3Gux9nPnLcG9yO_HxA,hLVEs7u6CVyfYbcGoUcQZw,1.0,1528058412,11,0,0,5MP-zvbSTUGz9Gmvv-jcrw
...,...,...,...,...,...,...,...,...
5242193,zziJLt25YU6dp01sewR-IQ,W535RAHI-mlftEIZvKakHg,5.0,1356245076,0,0,0,-uRNJrWttfxVxYudqyyMPA
4977915,zziJLt25YU6dp01sewR-IQ,BFgZyABXGpemsCrTqLWKxw,5.0,1365919457,1,0,0,aErazCRgFi6HwvUbfxUQPQ
3540730,zziJLt25YU6dp01sewR-IQ,3TN-ujStgKayyhu61EHdcQ,5.0,1365921867,1,0,0,klVjnSDIA4_Hxb3A65MKBQ
6428434,zziJLt25YU6dp01sewR-IQ,dCCBSvxEGT0yWIes0s4GeQ,5.0,1368950636,0,0,0,nU5t3ibV1SOsXSdk2eY_kQ
4735856,zziJLt25YU6dp01sewR-IQ,X3iMTTwv7yYSYp8Y-Y171w,5.0,1371928075,0,0,0,OLonjwZOpqhJHakVvbne0Q

In [8]:
# 分组&聚合
data_i = mini_inter_data.groupby(['item_id:token']).count()
data_i["count"] = data_i["user_id:token"]
# 筛选=>10 core
data_i = data_i[data_i["count"] >= 50]
data_i

,user_id:token,rating:float,timestamp:float,useful:float,funny:float,cool:float,review_id:token,count
item_id:token,,,,,,,,
-0G_6-KFGpCpxTUlVXCMYQ,50,50,50,50,50,50,50,50
-0TffRSXXIlBYVbb5AwfTg,304,304,304,304,304,304,304,304
-0iIxySkp97WNlwK66OGWg,63,63,63,63,63,63,63,63
-1B9pP_CrRBJYPICE5WbRA,205,205,205,205,205,205,205,205
-1PG6k_iezwJmRZLB7f6og,55,55,55,55,55,55,55,55
...,...,...,...,...,...,...,...,...
zwgBxmrmPBF6N2uRTUYXrQ,84,84,84,84,84,84,84,84
zwrgCMuZyFX46mL3piDyjg,176,176,176,176,176,176,176,176
zyPz0xvE5XkeCVH2J7g2gw,53,53,53,53,53,53,53,53
zz3E7kmJI2r2JseE6LAnrw,59,59,59,59,59,59,59,59
zzXDi0Pdv0s84M-oQaIa_g,88,88,88,88,88,88,88,88

In [9]:
# 按user_id筛选
mini_inter_data = mini_inter_data[mini_inter_data["item_id:token"].isin(data_i.index)]
mini_inter_data

,user_id:token,item_id:token,rating:float,timestamp:float,useful:float,funny:float,cool:float,review_id:token
5262245,--Vu3Gux9nPnLcG9yO_HxA,eGK4SEZakzmUzIKBfo_b2Q,1.0,1462312094,0,0,0,Xp3JUqi_ztPPcE47TWQlCQ
1642567,--Vu3Gux9nPnLcG9yO_HxA,j_AhCyEzJpo3sS7NZRFKQA,1.0,1493208089,1,1,1,wYttdXhyLXZkt98UiIGScA
1919366,--Vu3Gux9nPnLcG9yO_HxA,UNkOa6syMXonsoTErl2BIg,1.0,1502627982,2,0,0,RUkY2wCbepFC-sOTcNNqHA
6922378,--Vu3Gux9nPnLcG9yO_HxA,LbhraX3qY94g3Xn2Havbpg,1.0,1537438898,1,0,1,2K1nRwlB-zzuLcvroxnk-g
4272324,--Vu3Gux9nPnLcG9yO_HxA,wz8ZPfySQczcPgSyd33-HQ,3.0,1499666430,0,0,1,ln9seW2rHmfTEVGd7Uz-Ww
...,...,...,...,...,...,...,...,...
934027,zziJLt25YU6dp01sewR-IQ,PhjG3wOTXC054z4H8rrMsQ,4.0,1348761047,0,0,1,y0_ClE1KAEuBZVJHT4euVw
295098,zziJLt25YU6dp01sewR-IQ,1MdSDNxlCzKmYMMHSccVrQ,4.0,1351778085,0,0,0,1c8Ta3_JC7g6uqsVaLRX-w
4288218,zziJLt25YU6dp01sewR-IQ,UQMUtySn2q9cSObiw5UVsw,4.0,1362293908,0,0,0,us_mmIE32vpDmSUI5Jqbew
4977383,zziJLt25YU6dp01sewR-IQ,K3RURR9lIEE4JjOaPt99zg,5.0,1347780140,0,0,0,UuWc1gRitolwxdF38YbStg
3007097,zziJLt25YU6dp01sewR-IQ,BYuiZPNQ_i67VXl5b9BBSQ,5.0,1351429832,0,0,0,dn8oZL8EcYoXQ3DwkHeIwg

In [10]:
# mini_inter_data = inter_data[inter_data["item_id:token"].isin(mini_item_data['item_id:token'])][inter_data["user_id:token"].isin(mini_user_data['user_id:token'])]
# mini_inter_data

In [11]:
# 分组&聚合
data_u = mini_inter_data.groupby(['user_id:token']).count()
data_u["count"] = data_u["item_id:token"]
# 筛选=>10 core
data_u = data_u[data_u["count"] >= 50]
data_u

,item_id:token,rating:float,timestamp:float,useful:float,funny:float,cool:float,review_id:token,count
user_id:token,,,,,,,,
-3s52C4zL_DHRK0ULG6qtg,140,140,140,140,140,140,140,140
-7XrSrJfHndHc_taEXurTw,74,74,74,74,74,74,74,74
-7qUbOVWJp2NT3f_TNuIBA,81,81,81,81,81,81,81,81
-8PU0Z4Q2Nc-sY0eBj4DiQ,59,59,59,59,59,59,59,59
-B-QEUESGWHPE_889WJaeg,61,61,61,61,61,61,61,61
...,...,...,...,...,...,...,...,...
zvq6qxc2IVA08jaUelUMRw,77,77,77,77,77,77,77,77
zwXmvn1op5LuFF2Kveqaug,102,102,102,102,102,102,102,102
zxUwqykP_6m47BpJUZYSoQ,56,56,56,56,56,56,56,56
zyNrXvJyYdC34tS6BcCykA,73,73,73,73,73,73,73,73
zyvxtbh5eJ86bVgk52Yflg,181,181,181,181,181,181,181,181

In [12]:
# 按 user_id 筛选
mini_inter_data = mini_inter_data[mini_inter_data["user_id:token"].isin(data_u[:1000].index)]
mini_inter_data

,user_id:token,item_id:token,rating:float,timestamp:float,useful:float,funny:float,cool:float,review_id:token
6981068,-3s52C4zL_DHRK0ULG6qtg,89SD5fNDDnJj-ITB40hLsQ,1.0,1294923344,2,1,0,_v_4hY_Usl3kShOOvJ5Q7g
6861648,-3s52C4zL_DHRK0ULG6qtg,KWIapYSSHxfZ1NQFpV2S9g,1.0,1323279412,4,0,0,AO20GPrtj4arTImdmtUlgw
4054022,-3s52C4zL_DHRK0ULG6qtg,6Euj8bfFJ4aQ_cCi7aMWCw,1.0,1323467199,4,5,4,kNnAUWJufaBD1ylXLjPbhw
6209829,-3s52C4zL_DHRK0ULG6qtg,p6JxfR9ebAlIlpm674F-dg,1.0,1356366230,2,1,0,EYSrJL-lQdzHxwYT0KLAgQ
2659103,-3s52C4zL_DHRK0ULG6qtg,iOFbMitGdfU6i5xm4nZ8Ww,1.0,1389295015,9,1,2,QJEO92Cmy9ayvGJlzFPF_g
...,...,...,...,...,...,...,...,...
407095,IKbjLnfBQtEyVzEu8CuOLg,kKPJLiHIr9Gd9sYs3GhxDQ,5.0,1528039498,2,0,1,f4Owp9BLVY3Zq9u4UaANmA
3934417,IKbjLnfBQtEyVzEu8CuOLg,wEdzUMaLE2ebYoe7Z0XGaA,5.0,1529687592,3,1,2,ffkbuHSApSnFEVKPrZ0lqg
6692486,IKbjLnfBQtEyVzEu8CuOLg,HHD86HwgGB8oHlc04VT1VQ,5.0,1543756973,2,0,2,FiwxdC8KhN2Sp3Aegq2iBw
1838728,IKbjLnfBQtEyVzEu8CuOLg,c7ZxVUJVjEOe9hLhvKGnDA,5.0,1550224571,2,0,3,cwjhDiucYyg7pU0L_HCI5Q
2041105,IKbjLnfBQtEyVzEu8CuOLg,DsPomqfQZ44v5wD-My6dIQ,5.0,1564135778,3,0,2,xmst46r6sxXIIpAIbjhN9g

In [13]:
mini_data_u = data_u[:1000].reset_index().reset_index().rename(columns={'index': 'user_id'})
mini_data_u

,user_id,user_id:token,item_id:token,rating:float,timestamp:float,useful:float,funny:float,cool:float,review_id:token,count
0,0,-3s52C4zL_DHRK0ULG6qtg,140,140,140,140,140,140,140,140
1,1,-7XrSrJfHndHc_taEXurTw,74,74,74,74,74,74,74,74
2,2,-7qUbOVWJp2NT3f_TNuIBA,81,81,81,81,81,81,81,81
3,3,-8PU0Z4Q2Nc-sY0eBj4DiQ,59,59,59,59,59,59,59,59
4,4,-B-QEUESGWHPE_889WJaeg,61,61,61,61,61,61,61,61
...,...,...,...,...,...,...,...,...,...,...
995,995,IEbdk3v9uCl20UVObqljvA,89,89,89,89,89,89,89,89
996,996,IGgXA7f9zt6KAoeaIQux3w,55,55,55,55,55,55,55,55
997,997,IH0ToaZ8hJXO2pVieN7dpQ,154,154,154,154,154,154,154,154
998,998,IJVqc_5NmUflKafvFyKqmQ,110,110,110,110,110,110,110,110
999,999,IKbjLnfBQtEyVzEu8CuOLg,471,471,471,471,471,471,471,471

In [14]:
mini_inter_data['user_id'] = mini_inter_data['user_id:token'].factorize()[0]
mini_inter_data['item_id'] = mini_inter_data['item_id:token'].factorize()[0]
mini_inter_data

C:\Users\82735\AppData\Local\Temp\ipykernel_24376\1035680129.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mini_inter_data['user_id'] = mini_inter_data['user_id:token'].factorize()[0]
C:\Users\82735\AppData\Local\Temp\ipykernel_24376\1035680129.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mini_inter_data['item_id'] = mini_inter_data['item_id:token'].factorize()[0]

,user_id:token,item_id:token,rating:float,timestamp:float,useful:float,funny:float,cool:float,review_id:token,user_id,item_id
6981068,-3s52C4zL_DHRK0ULG6qtg,89SD5fNDDnJj-ITB40hLsQ,1.0,1294923344,2,1,0,_v_4hY_Usl3kShOOvJ5Q7g,0,0
6861648,-3s52C4zL_DHRK0ULG6qtg,KWIapYSSHxfZ1NQFpV2S9g,1.0,1323279412,4,0,0,AO20GPrtj4arTImdmtUlgw,0,1
4054022,-3s52C4zL_DHRK0ULG6qtg,6Euj8bfFJ4aQ_cCi7aMWCw,1.0,1323467199,4,5,4,kNnAUWJufaBD1ylXLjPbhw,0,2
6209829,-3s52C4zL_DHRK0ULG6qtg,p6JxfR9ebAlIlpm674F-dg,1.0,1356366230,2,1,0,EYSrJL-lQdzHxwYT0KLAgQ,0,3
2659103,-3s52C4zL_DHRK0ULG6qtg,iOFbMitGdfU6i5xm4nZ8Ww,1.0,1389295015,9,1,2,QJEO92Cmy9ayvGJlzFPF_g,0,4
...,...,...,...,...,...,...,...,...,...,...
407095,IKbjLnfBQtEyVzEu8CuOLg,kKPJLiHIr9Gd9sYs3GhxDQ,5.0,1528039498,2,0,1,f4Owp9BLVY3Zq9u4UaANmA,999,2566
3934417,IKbjLnfBQtEyVzEu8CuOLg,wEdzUMaLE2ebYoe7Z0XGaA,5.0,1529687592,3,1,2,ffkbuHSApSnFEVKPrZ0lqg,999,2507
6692486,IKbjLnfBQtEyVzEu8CuOLg,HHD86HwgGB8oHlc04VT1VQ,5.0,1543756973,2,0,2,FiwxdC8KhN2Sp3Aegq2iBw,999,4102
1838728,IKbjLnfBQtEyVzEu8CuOLg,c7ZxVUJVjEOe9hLhvKGnDA,5.0,1550224571,2,0,3,cwjhDiucYyg7pU0L_HCI5Q,999,4319
2041105,IKbjLnfBQtEyVzEu8CuOLg,DsPomqfQZ44v5wD-My6dIQ,5.0,1564135778,3,0,2,xmst46r6sxXIIpAIbjhN9g,999,2595

In [15]:
inter_data = mini_inter_data
inter_data

,user_id:token,item_id:token,rating:float,timestamp:float,useful:float,funny:float,cool:float,review_id:token,user_id,item_id
6981068,-3s52C4zL_DHRK0ULG6qtg,89SD5fNDDnJj-ITB40hLsQ,1.0,1294923344,2,1,0,_v_4hY_Usl3kShOOvJ5Q7g,0,0
6861648,-3s52C4zL_DHRK0ULG6qtg,KWIapYSSHxfZ1NQFpV2S9g,1.0,1323279412,4,0,0,AO20GPrtj4arTImdmtUlgw,0,1
4054022,-3s52C4zL_DHRK0ULG6qtg,6Euj8bfFJ4aQ_cCi7aMWCw,1.0,1323467199,4,5,4,kNnAUWJufaBD1ylXLjPbhw,0,2
6209829,-3s52C4zL_DHRK0ULG6qtg,p6JxfR9ebAlIlpm674F-dg,1.0,1356366230,2,1,0,EYSrJL-lQdzHxwYT0KLAgQ,0,3
2659103,-3s52C4zL_DHRK0ULG6qtg,iOFbMitGdfU6i5xm4nZ8Ww,1.0,1389295015,9,1,2,QJEO92Cmy9ayvGJlzFPF_g,0,4
...,...,...,...,...,...,...,...,...,...,...
407095,IKbjLnfBQtEyVzEu8CuOLg,kKPJLiHIr9Gd9sYs3GhxDQ,5.0,1528039498,2,0,1,f4Owp9BLVY3Zq9u4UaANmA,999,2566
3934417,IKbjLnfBQtEyVzEu8CuOLg,wEdzUMaLE2ebYoe7Z0XGaA,5.0,1529687592,3,1,2,ffkbuHSApSnFEVKPrZ0lqg,999,2507
6692486,IKbjLnfBQtEyVzEu8CuOLg,HHD86HwgGB8oHlc04VT1VQ,5.0,1543756973,2,0,2,FiwxdC8KhN2Sp3Aegq2iBw,999,4102
1838728,IKbjLnfBQtEyVzEu8CuOLg,c7ZxVUJVjEOe9hLhvKGnDA,5.0,1550224571,2,0,3,cwjhDiucYyg7pU0L_HCI5Q,999,4319
2041105,IKbjLnfBQtEyVzEu8CuOLg,DsPomqfQZ44v5wD-My6dIQ,5.0,1564135778,3,0,2,xmst46r6sxXIIpAIbjhN9g,999,2595

In [16]:
user_data

,user_id:token,user_name:token,user_review_count:float,yelping_since:float,user_useful:float,user_funny:float,user_cool:float,elite:token,fans:float,average_stars:float,...,compliment_more:float,compliment_profile:float,compliment_cute:float,compliment_list:float,compliment_note:float,compliment_plain:float,compliment_cool:float,compliment_funny:float,compliment_writer:float,compliment_photos:float
397935,---1lKK3aKOuomHnwAkAow,Monera,266,2007-06-04 01:37:45,510,181,206,"2010,2011,2012",17,3.93,...,3,2,1,0,5,9,9,9,9,0
27105,---2PmXbF47D870stH1jqA,Susan,36,2012-10-24 13:20:46,63,4,36,NaN,3,4.98,...,0,0,0,0,0,2,0,0,2,0
90950,---UgP94gokyCDuB5zUssA,Leonel,16,2014-11-02 14:53:16,8,0,3,NaN,1,3.44,...,0,0,0,0,1,1,0,0,0,0
1067802,---fa6ZK37T9NjkGKI4oSg,Jan,8,2015-02-02 19:59:04,9,0,0,NaN,0,2.78,...,0,0,0,0,0,0,0,0,0,0
78319,---r61b7EpVPkb4UVme5tA,Brian,6,2013-02-07 00:35:37,10,2,3,NaN,1,4.17,...,0,0,0,0,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
325050,zzz-M4QvkEpUWWPL9RTzLA,Kimberly,20,2013-11-11 18:10:25,21,9,13,NaN,1,3.00,...,0,0,0,0,1,1,0,0,0,0
418191,zzzCg-_lpyYE82TlJCdwdw,Anna,4,2013-01-01 18:49:09,16,5,1,NaN,0,4.00,...,0,0,0,0,0,0,0,0,0,0
827569,zzzGgfvrSJ4AQeKtcgocIw,Tracy,4,2015-10-05 17:08:18,7,1,1,NaN,0,2.83,...,0,0,0,0,0,1,0,0,0,0
1102863,zzzMBVS73g3ZJ7qL8JyhiA,Bee,1,2020-02-21 23:39:44,0,0,0,NaN,0,1.00,...,0,0,0,0,0,0,0,0,0,0
1896559,zzzUFM4HFe0SFG0bPjntQA,B,4,2014-11-24 15:10:48,2,0,0,NaN,0,2.00,...,0,0,0,0,0,1,0,0,0,0

In [17]:
mini_user_data = user_data[user_data["user_id:token"].isin(inter_data['user_id:token'])]
mini_user_data = pd.merge(mini_user_data, inter_data.groupby(['user_id:token','user_id']).count().reset_index()[['user_id:token','user_id']], on='user_id:token', how='left')
mini_user_data

,user_id:token,user_name:token,user_review_count:float,yelping_since:float,user_useful:float,user_funny:float,user_cool:float,elite:token,fans:float,average_stars:float,...,compliment_profile:float,compliment_cute:float,compliment_list:float,compliment_note:float,compliment_plain:float,compliment_cool:float,compliment_funny:float,compliment_writer:float,compliment_photos:float,user_id
0,-3s52C4zL_DHRK0ULG6qtg,Sara,1760,2010-05-16 16:21:33,1663,476,368,"2010,2011,2012,2013,2014,2015,2016,2017,2018,2019",55,3.46,...,1,2,0,20,47,20,20,12,2,0
1,-7XrSrJfHndHc_taEXurTw,Paul,381,2014-07-04 12:27:52,557,155,263,"2015,2016,2017",8,4.34,...,0,0,0,6,10,19,19,19,6,1
2,-7qUbOVWJp2NT3f_TNuIBA,Betsy,166,2014-08-01 23:28:04,389,43,193,"2019,20,20,2021",13,4.42,...,0,0,0,4,16,12,12,32,7,2
3,-8PU0Z4Q2Nc-sY0eBj4DiQ,David,126,2011-07-20 14:26:49,196,29,96,"2017,2018",9,4.50,...,0,0,0,5,9,6,6,8,3,3
4,-B-QEUESGWHPE_889WJaeg,Mark,1014,2009-05-31 06:02:42,3817,1689,2529,"2011,2012,2013,2014,2015,2016,2017,2018,2019,2...",200,3.41,...,10,4,5,89,294,286,286,82,198,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,IEbdk3v9uCl20UVObqljvA,Augustina,159,2013-10-04 14:31:24,94,31,24,"2017,2018,2019",3,3.70,...,0,0,0,2,4,3,3,0,1,995
996,IGgXA7f9zt6KAoeaIQux3w,Pat,151,2016-07-18 22:08:25,130,6,60,"2018,2019,20,20,2021",5,4.14,...,0,0,0,22,2,8,8,3,2,996
997,IH0ToaZ8hJXO2pVieN7dpQ,Andrea,453,2015-07-18 16:06:23,1815,504,1125,"2017,2018,2019,20,20,2021",67,4.34,...,1,1,0,26,45,59,59,49,50,997
998,IJVqc_5NmUflKafvFyKqmQ,Mike,415,2015-02-08 16:53:54,663,159,312,"2016,2017,2018,2019,20,20,2021",20,3.64,...,0,0,0,23,16,14,14,16,16,998
999,IKbjLnfBQtEyVzEu8CuOLg,Erica,800,2010-01-02 04:59:57,1571,290,671,"2012,2013,2014,2015,2016,2017,2019",64,3.87,...,1,2,0,30,67,57,57,47,1,999

In [18]:
mini_item_data = item_data[item_data["item_id:token"].isin(inter_data['item_id:token'])]
mini_item_data = pd.merge(mini_item_data, inter_data.groupby(['item_id:token','item_id']).count().reset_index()[['item_id:token','item_id']], on='item_id:token', how='left')
mini_item_data

,item_id:token,item_name:token_seq,address:token_seq,city:token_seq,state:token,postal_code:token,latitude:float,longitude:float,item_stars:float,item_review_count:float,is_open:float,categories:token_seq,item_id
0,-0G_6-KFGpCpxTUlVXCMYQ,Gio Taco,350 E Congress St,Tucson,AZ,85701,32.221294,-110.965698,3.5,148,0,"Restaurants, Mexican",4820
1,-0TffRSXXIlBYVbb5AwfTg,IndeBlue Modern Indian Food & Spirits,205 South 13th St,Philadelphia,PA,19107,39.948508,-75.161969,4.5,1097,1,"Cocktail Bars, Food Delivery Services, Nightli...",1162
2,-0iIxySkp97WNlwK66OGWg,Truckee Bagel Company - Midtown,"538 S Virginia St, Ste B",Reno,NV,89501,39.520240,-119.810022,3.5,219,1,"Caterers, Sandwiches, Coffee & Tea, Bagels, Fo...",744
3,-1B9pP_CrRBJYPICE5WbRA,Spice 28,1228 Chestnut St,Philadelphia,PA,19107,39.950352,-75.161583,4.0,822,1,"Asian Fusion, Restaurants, American (New), Tha...",1242
4,-1PG6k_iezwJmRZLB7f6og,The Lemon Bar,95 E Pine St,Zionsville,IN,46077,39.950010,-86.260516,4.0,165,1,"Food, Cocktail Bars, American (New), Restauran...",4516
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5509,zwgBxmrmPBF6N2uRTUYXrQ,Sugars,225 Church St,Philadelphia,PA,19106,39.950992,-75.144882,3.5,148,0,"Pubs, Nightlife, Bars, Restaurants, Dive Bars",3504
5510,zwrgCMuZyFX46mL3piDyjg,Cup Cafe,311 E Congress St,Tucson,AZ,85701,32.222199,-110.966626,4.0,862,1,"Breakfast & Brunch, Bars, Restaurants, Food, N...",247
5511,zyPz0xvE5XkeCVH2J7g2gw,Von Elrod's Beer Hall & Kitchen,1004 4th Ave N,Nashville,TN,37219,36.173749,-86.784954,3.5,280,1,"Pretzels, Barbeque, American (New), Hot Dogs, ...",4304
5512,zz3E7kmJI2r2JseE6LAnrw,Hung Vuong Super Market,1122 Washington Ave,Philadelphia,PA,19147,39.936582,-75.162655,3.5,99,1,"Food, Grocery, International Grocery",664
5513,zzXDi0Pdv0s84M-oQaIa_g,Radnor Lake State Park,1160 Otter Creek Rd,Nashville,TN,37220,36.062764,-86.809891,4.5,205,1,"Hiking, Lakes, Museums, Parks, Arts & Entertai...",2983

In [19]:
item_data=mini_item_data
user_data=mini_user_data

In [20]:
user_data.columns,item_data.columns

(Index(['user_id:token', 'user_name:token', 'user_review_count:float',
        'yelping_since:float', 'user_useful:float', 'user_funny:float',
        'user_cool:float', 'elite:token', 'fans:float', 'average_stars:float',
        'compliment_hot:float', 'compliment_more:float',
        'compliment_profile:float', 'compliment_cute:float',
        'compliment_list:float', 'compliment_note:float',
        'compliment_plain:float', 'compliment_cool:float',
        'compliment_funny:float', 'compliment_writer:float',
        'compliment_photos:float', 'user_id'],
       dtype='object'),
 Index(['item_id:token', 'item_name:token_seq', 'address:token_seq',
        'city:token_seq', 'state:token', 'postal_code:token', 'latitude:float',
        'longitude:float', 'item_stars:float', 'item_review_count:float',
        'is_open:float', 'categories:token_seq', 'item_id'],
       dtype='object'))

In [21]:
#### 构建基础数据完毕

In [22]:
threshold = 3
max_length = 10
user_temp = "user name: {user_name}, fans count: {fans_count}, user review count: {user_review_count}, user useful count: {user_useful_count}, user funny count: {user_funny_count}, average stars: {average_stars}, compliment hot count: {compliment_hot}, compliment more count: {compliment_more}, compliment profile count: {compliment_profile}, compliment cute count: {compliment_cute}, compliment list count: {compliment_list}, compliment note count: {compliment_note}, compliment plain count: {compliment_plain}, compliment cool count: {compliment_cool}, compliment funny count: {compliment_funny}, compliment writer count: {compliment_writer}, compliment photos count: {compliment_photos}."
item_temp = "item name: {item_name}, address: {address_city_state}, zipcode: {zipcode}, item stars: {item_stars}, item review count: {item_review_count}, is open:{is_open}, category: {category}, likes count: {likes_count}, dislikes count: {dislikes_count}, liking rate: {liking_rate}."

user_temp1 = "user name: {user_name}, fans count: {fans_count}, user review count: {user_review_count}, user useful count: {user_useful_count}, user funny count: {user_funny_count}, average stars: {average_stars}, compliment hot count: {compliment_hot}, compliment more count: {compliment_more}, compliment profile count: {compliment_profile}, compliment cute count: {compliment_cute}, compliment list count: {compliment_list}, compliment note count: {compliment_note}, compliment plain count: {compliment_plain}, compliment cool count: {compliment_cool}, compliment funny count: {compliment_funny}, compliment writer count: {compliment_writer}, compliment photos count: {compliment_photos}."
item_temp1 = "item name: {item_name}, address: {address_city_state}, zipcode: {zipcode}, item stars: {item_stars}, item review count: {item_review_count}, is open:{is_open}, category: {category}."

user_train_temp = """You are a recommendation system that gives you a list of items that the user likes and dislikes, and predicts whether the user will like the target item or not. Returns only whether the user likes the target movie: Yes or No. # noqa: E501

User Information:
{user_info}

Likes List:
{likes_list}

Dislikes List:
{dislikes_list}

Target Item:
{targe_item}
"""

In [23]:
inter_data

,user_id:token,item_id:token,rating:float,timestamp:float,useful:float,funny:float,cool:float,review_id:token,user_id,item_id
6981068,-3s52C4zL_DHRK0ULG6qtg,89SD5fNDDnJj-ITB40hLsQ,1.0,1294923344,2,1,0,_v_4hY_Usl3kShOOvJ5Q7g,0,0
6861648,-3s52C4zL_DHRK0ULG6qtg,KWIapYSSHxfZ1NQFpV2S9g,1.0,1323279412,4,0,0,AO20GPrtj4arTImdmtUlgw,0,1
4054022,-3s52C4zL_DHRK0ULG6qtg,6Euj8bfFJ4aQ_cCi7aMWCw,1.0,1323467199,4,5,4,kNnAUWJufaBD1ylXLjPbhw,0,2
6209829,-3s52C4zL_DHRK0ULG6qtg,p6JxfR9ebAlIlpm674F-dg,1.0,1356366230,2,1,0,EYSrJL-lQdzHxwYT0KLAgQ,0,3
2659103,-3s52C4zL_DHRK0ULG6qtg,iOFbMitGdfU6i5xm4nZ8Ww,1.0,1389295015,9,1,2,QJEO92Cmy9ayvGJlzFPF_g,0,4
...,...,...,...,...,...,...,...,...,...,...
407095,IKbjLnfBQtEyVzEu8CuOLg,kKPJLiHIr9Gd9sYs3GhxDQ,5.0,1528039498,2,0,1,f4Owp9BLVY3Zq9u4UaANmA,999,2566
3934417,IKbjLnfBQtEyVzEu8CuOLg,wEdzUMaLE2ebYoe7Z0XGaA,5.0,1529687592,3,1,2,ffkbuHSApSnFEVKPrZ0lqg,999,2507
6692486,IKbjLnfBQtEyVzEu8CuOLg,HHD86HwgGB8oHlc04VT1VQ,5.0,1543756973,2,0,2,FiwxdC8KhN2Sp3Aegq2iBw,999,4102
1838728,IKbjLnfBQtEyVzEu8CuOLg,c7ZxVUJVjEOe9hLhvKGnDA,5.0,1550224571,2,0,3,cwjhDiucYyg7pU0L_HCI5Q,999,4319
2041105,IKbjLnfBQtEyVzEu8CuOLg,DsPomqfQZ44v5wD-My6dIQ,5.0,1564135778,3,0,2,xmst46r6sxXIIpAIbjhN9g,999,2595

In [24]:
def build_item_other(row):
    df1 = inter_data[inter_data['item_id:token'] == row['item_id:token']]
    total = df1.shape[0]
    likes_count = df1[df1['rating:float'] > threshold].shape[0]
    dislikes_count = total - likes_count
    liking_rate = round(likes_count/total, 4)
    return {'likes_count':likes_count,'dislikes_count':dislikes_count,'liking_rate':liking_rate}

In [25]:
item_data['other'] = item_data.apply(lambda row: build_item_other(row), axis=1)
item_data['other'].iloc[0]

{'likes_count': 6, 'dislikes_count': 3, 'liking_rate': 0.6667}

In [26]:
# 拼接信息, json
item_data['info'] = item_data.apply(lambda row: {'text':item_temp.replace('{item_name}',row["item_name:token_seq"]).replace('{item_id}',str(row["item_id"])).replace('{address_city_state}',f'{row["address:token_seq"]},{row["city:token_seq"]},{row["state:token"]}').replace('{zipcode}',row["postal_code:token"])
.replace('{item_stars}',str(row["item_stars:float"])).replace('{item_review_count}',str(row["item_review_count:float"])).replace('{is_open}',str(row["is_open:float"])).replace('{category}',row["categories:token_seq"]).replace('{likes_count}',str(row['other']["likes_count"])).replace('{dislikes_count}',str(row['other']["dislikes_count"])).replace('{liking_rate}',str(row['other']["liking_rate"]))}, axis=1)
item_data['info'].iloc[0]

{'text': 'item name: Gio Taco, address: 350 E Congress St,Tucson,AZ, zipcode: 85701, item stars: 3.5, item review count: 148, is open:0, category: Restaurants, Mexican, likes count: 6, dislikes count: 3, liking rate: 0.6667.'}

In [27]:
item_data.iloc[2]

item_id:token                                         -0iIxySkp97WNlwK66OGWg
item_name:token_seq                          Truckee Bagel Company - Midtown
address:token_seq                                   538 S Virginia St, Ste B
city:token_seq                                                          Reno
state:token                                                               NV
postal_code:token                                                      89501
latitude:float                                                      39.52024
longitude:float                                                  -119.810022
item_stars:float                                                         3.5
item_review_count:float                                                  219
is_open:float                                                              1
categories:token_seq       Caterers, Sandwiches, Coffee & Tea, Bagels, Fo...
item_id                                                                  744
other                      {'likes_count': 7, 'dislikes_count': 3, 'likin...
info                       {'text': 'item name: Truckee Bagel Company - M...
Name: 2, dtype: object

In [28]:
inter_data

,user_id:token,item_id:token,rating:float,timestamp:float,useful:float,funny:float,cool:float,review_id:token,user_id,item_id
6981068,-3s52C4zL_DHRK0ULG6qtg,89SD5fNDDnJj-ITB40hLsQ,1.0,1294923344,2,1,0,_v_4hY_Usl3kShOOvJ5Q7g,0,0
6861648,-3s52C4zL_DHRK0ULG6qtg,KWIapYSSHxfZ1NQFpV2S9g,1.0,1323279412,4,0,0,AO20GPrtj4arTImdmtUlgw,0,1
4054022,-3s52C4zL_DHRK0ULG6qtg,6Euj8bfFJ4aQ_cCi7aMWCw,1.0,1323467199,4,5,4,kNnAUWJufaBD1ylXLjPbhw,0,2
6209829,-3s52C4zL_DHRK0ULG6qtg,p6JxfR9ebAlIlpm674F-dg,1.0,1356366230,2,1,0,EYSrJL-lQdzHxwYT0KLAgQ,0,3
2659103,-3s52C4zL_DHRK0ULG6qtg,iOFbMitGdfU6i5xm4nZ8Ww,1.0,1389295015,9,1,2,QJEO92Cmy9ayvGJlzFPF_g,0,4
...,...,...,...,...,...,...,...,...,...,...
407095,IKbjLnfBQtEyVzEu8CuOLg,kKPJLiHIr9Gd9sYs3GhxDQ,5.0,1528039498,2,0,1,f4Owp9BLVY3Zq9u4UaANmA,999,2566
3934417,IKbjLnfBQtEyVzEu8CuOLg,wEdzUMaLE2ebYoe7Z0XGaA,5.0,1529687592,3,1,2,ffkbuHSApSnFEVKPrZ0lqg,999,2507
6692486,IKbjLnfBQtEyVzEu8CuOLg,HHD86HwgGB8oHlc04VT1VQ,5.0,1543756973,2,0,2,FiwxdC8KhN2Sp3Aegq2iBw,999,4102
1838728,IKbjLnfBQtEyVzEu8CuOLg,c7ZxVUJVjEOe9hLhvKGnDA,5.0,1550224571,2,0,3,cwjhDiucYyg7pU0L_HCI5Q,999,4319
2041105,IKbjLnfBQtEyVzEu8CuOLg,DsPomqfQZ44v5wD-My6dIQ,5.0,1564135778,3,0,2,xmst46r6sxXIIpAIbjhN9g,999,2595

In [29]:
inter_data = inter_data.groupby('user_id:token').agg(list).reset_index()
inter_data

,user_id:token,item_id:token,rating:float,timestamp:float,useful:float,funny:float,cool:float,review_id:token,user_id,item_id
0,-3s52C4zL_DHRK0ULG6qtg,"[89SD5fNDDnJj-ITB40hLsQ, KWIapYSSHxfZ1NQFpV2S9...","[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ...","[1294923344, 1323279412, 1323467199, 135636623...","[2, 4, 4, 2, 9, 1, 3, 4, 1, 1, 0, 0, 1, 0, 1, ...","[1, 0, 5, 1, 1, 1, 2, 0, 1, 0, 0, 0, 0, 0, 0, ...","[0, 0, 4, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[_v_4hY_Usl3kShOOvJ5Q7g, AO20GPrtj4arTImdmtUlg...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,..."
1,-7XrSrJfHndHc_taEXurTw,"[lU3elCfnhoOAhkR6FewPSA, UnBs9SfFGQ7TpE_3uYIqf...","[2.0, 3.0, 3.0, 3.0, 3.0, 3.0, 4.0, 4.0, 4.0, ...","[1429410657, 1408684146, 1429279837, 144138893...","[0, 2, 1, 0, 0, 0, 4, 0, 1, 2, 0, 4, 1, 0, 1, ...","[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, ...","[mH75LDGfUy9VFOdzHfX4Jg, n9lfW0-8ts4kY50_-5Zra...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[124, 125, 126, 127, 128, 129, 130, 131, 132, ..."
2,-7qUbOVWJp2NT3f_TNuIBA,"[5P4w4WfPbXzUi6YALfwx2g, KAQT1EGptJDTVMTslyBdw...","[2.0, 3.0, 3.0, 3.0, 4.0, 4.0, 4.0, 4.0, 4.0, ...","[1427567857, 1583062705, 1592829485, 161694496...","[7, 3, 1, 3, 1, 1, 0, 0, 2, 0, 1, 1, 1, 0, 0, ...","[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, ...","[0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, ...","[qF7qlKlQaUYu-K8EoXoFpA, hech72OZcGGFNH-KZAPCm...","[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ...","[198, 199, 200, 201, 202, 203, 204, 205, 206, ..."
3,-8PU0Z4Q2Nc-sY0eBj4DiQ,"[Mzmt8AvZOExG_4h3MMlihg, aOJDVHCn9iBIC33l_2HTR...","[1.0, 1.0, 1.0, 1.0, 2.0, 2.0, 2.0, 3.0, 3.0, ...","[1312890289, 1325260403, 1410770590, 159689884...","[5, 0, 3, 1, 1, 3, 2, 2, 1, 2, 1, 2, 0, 2, 1, ...","[1, 0, 1, 0, 0, 2, 0, 1, 0, 0, 0, 0, 0, 0, 2, ...","[0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, ...","[-oWqibdb85wMFR3WcmiWJQ, c-HwAg6rxtdmBTYoKQplD...","[3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, ...","[167, 273, 274, 275, 276, 277, 278, 279, 280, ..."
4,-B-QEUESGWHPE_889WJaeg,"[EtM079Cj7-B3G7jPsGYb_Q, thlyktt2c7v1DyOpSVSib...","[1.0, 1.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, ...","[1305974143, 1433573965, 1272706200, 130476059...","[5, 13, 1, 1, 10, 8, 10, 13, 5, 0, 0, 1, 1, 1,...","[1, 4, 0, 1, 6, 4, 1, 3, 1, 1, 0, 0, 1, 0, 0, ...","[0, 6, 0, 0, 5, 4, 2, 4, 2, 0, 0, 2, 0, 1, 1, ...","[ql-A6eeHNtBDb0VimRxVWA, khyLRislYJenRHLhvvi8L...","[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, ...","[320, 321, 322, 323, 321, 324, 324, 325, 326, ..."
...,...,...,...,...,...,...,...,...,...,...
995,IEbdk3v9uCl20UVObqljvA,"[4_W5pstoN1166TGjjPOrMg, Lw1gzZZGI2GFQc6BI5zyJ...","[1.0, 1.0, 1.0, 1.0, 2.0, 2.0, 2.0, 2.0, 2.0, ...","[1425215995, 1425218338, 1426245378, 143414699...","[0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 4, 1, 0, 0, 0, ...","[0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, ...","[PW3RQPwW49ePh25G4j1rVg, 3AIn_JaK4GPv4Q3F89MiG...","[995, 995, 995, 995, 995, 995, 995, 995, 995, ...","[3323, 1506, 590, 2370, 793, 2708, 665, 4763, ..."
996,IGgXA7f9zt6KAoeaIQux3w,"[Xm3fazqrD-Fi4tVPlc4i6Q, MiAG-Q8SjjHNEnN5MaEEj...","[1.0, 1.0, 1.0, 1.0, 2.0, 3.0, 3.0, 3.0, 3.0, ...","[1513677297, 1531763443, 1604512637, 163067707...","[1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, ...","[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[6iSIl93AzqvR84tU7oiFHw, ZwB5HCWmGCDd6whL9o5Pm...","[996, 996, 996, 996, 996, 996, 996, 996, 996, ...","[529, 5290, 4368, 1445, 452, 510, 933, 519, 90..."
997,IH0ToaZ8hJXO2pVieN7dpQ,"[AGlh4ZDv6jnoiYfz7At9mw, jS3affmkXWrBnidXA-DIf...","[2.0, 2.0, 2.0, 2.0, 2.0, 3.0, 3.0, 3.0, 3.0, ...","[1482401149, 1513926358, 1517684210, 152266367...","[0, 3, 3, 2, 5, 2, 3, 0, 1, 6, 5, 1, 3, 3, 6, ...","[0, 1, 0, 2, 2, 1, 1, 2, 1, 3, 0, 0, 1, 0, 1, ...","[0, 0, 0, 0, 2, 2, 2, 0, 1, 2, 0, 0, 1, 0, 0, ...","[g9fbl1d6w5fjcNips0nbnA, CP34riIFF6ne4p6O54Fwo...","[997, 997, 997, 997, 997, 997, 997, 997, 997, ...","[593, 2240, 593, 4802, 3321, 1207, 2902, 647, ..."
998,IJVqc_5NmUflKafvFyKqmQ,"[YvrV_Tc9syF2Wch0HOIT3A, YvrV_Tc9syF2Wch0HOIT3...","[1.0, 1.0, 2.0, 2.0, 2.0, 3.0, 3.0, 3.0, 3.0, ...","[1554381399, 1556173167, 1432466610, 154479287...","[0, 1, 6, 1, 0, 1, 0, 0, 2, 2, 3, 2, 5, 1, 2, ...","[1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 2, 1, 0, 0, 0, ...","[0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, ...","[AAIQEvoU-4JWw98Z4YqWFA, M_DRHGvbQoPMAtVkmvEa6...","[998, 998, 998, 998, 998, 998, 998, 998, 998, ...","[3586, 3586, 1980, 1133, 4291, 1991, 1771, 426..."
999,IKbjLnfBQtEyVzEu8CuOLg,"[QGYzYUMsQe6k7__LD91E5w, EzjysPg2-lVX1E0ibStUX...","[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 2.0, ...","[1284005097, 1315024020, 1336849342, 133736682...","[2, 1, 6, 1, 0, 0, 1, 1, 0, 1, 5, 0, 0, 1, 0, ...","[0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[DyKKAL0OYNab1I6rerDL8Q, kGiZuNxhMQFgEmKhbzzfa...","[999, 999, 999, 999, 999, 999, 999, 999, 999, ...","[830, 2628, 2651, 4005, 2625, 2708, 164, 630, ..."

In [30]:
def cal_arr(ls,num):
    arr = []
    for i in range(0, len(ls), num):
        a1 = ls[i:i+num]
        if len(a1)==num:
            arr.append(a1)
    return arr
def build_user_inter(row):
    rs = row['rating:float']
    p_len = len([x for x in rs if x > threshold])
    p_rs = rs[:p_len]
    n_rs = rs[p_len:]

    ids = row['item_id']
    p_id_groups = ids[:p_len]
    n_id_groups = ids[p_len:]

    # 6p,4n
    p_num,n_num = 6,4
    p_rs1 = cal_arr(p_rs,p_num)
    n_rs1 = cal_arr(n_rs,n_num)

    p_id_groups1 = cal_arr(p_id_groups,p_num)
    n_id_groups1 = cal_arr(n_id_groups,n_num)
    
    # 对齐两个列表
    min_num = min(len(p_rs1), len(n_rs1))
    p_rs = p_rs1[:min_num]
    n_rs = n_rs1[:min_num]

    p_id_groups = p_id_groups1[:min_num]
    n_id_groups = n_id_groups1[:min_num]

    inter = {'p_id_groups': p_id_groups, 'n_id_groups': n_id_groups, 'p_rs': p_rs, 'n_rs': n_rs}
    return inter

inter_data['user_inter'] = inter_data.apply(lambda row: build_user_inter(row), axis=1)
inter_data.iloc[0]

user_id:token                                 -3s52C4zL_DHRK0ULG6qtg
item_id:token      [89SD5fNDDnJj-ITB40hLsQ, KWIapYSSHxfZ1NQFpV2S9...
rating:float       [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ...
timestamp:float    [1294923344, 1323279412, 1323467199, 135636623...
useful:float       [2, 4, 4, 2, 9, 1, 3, 4, 1, 1, 0, 0, 1, 0, 1, ...
funny:float        [1, 0, 5, 1, 1, 1, 2, 0, 1, 0, 0, 0, 0, 0, 0, ...
cool:float         [0, 0, 4, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
review_id:token    [_v_4hY_Usl3kShOOvJ5Q7g, AO20GPrtj4arTImdmtUlg...
user_id            [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
item_id            [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...
user_inter         {'p_id_groups': [[0, 1, 2, 3, 4, 5], [6, 7, 8,...
Name: 0, dtype: object

In [31]:
# 拼接信息, json
user_data['info'] = user_data.apply(lambda row: {'text':user_temp.replace('{user_id}',str(row["user_id"])).replace('{user_name}',str(row["user_name:token"])).replace('{fans_count}',str(row["fans:float"])).replace('{user_review_count}',str(row["user_review_count:float"])).replace('{user_useful_count}',str(row["user_useful:float"])).replace('{user_funny_count}',str(row["user_funny:float"])).replace('{average_stars}',str(row["average_stars:float"])).replace('{compliment_hot}',str(row["compliment_hot:float"])).replace('{compliment_more}',str(row["compliment_more:float"])).replace('{compliment_profile}',str(row["compliment_profile:float"])).replace('{compliment_cute}',str(row["compliment_cute:float"])).replace('{compliment_list}',str(row["compliment_list:float"])).replace('{compliment_note}',str(row["compliment_note:float"])).replace('{compliment_plain}',str(row["compliment_plain:float"])).replace('{compliment_cool}',str(row["compliment_cool:float"])).replace('{compliment_funny}',str(row["compliment_funny:float"])).replace('{compliment_writer}',str(row["compliment_writer:float"])).replace('{compliment_photos}',str(row["compliment_photos:float"]))}, axis=1)
user_data['info'].iloc[0]

{'text': 'user name: Sara, fans count: 55, user review count: 1760, user useful count: 1663, user funny count: 476, average stars: 3.46, compliment hot count: 11, compliment more count: 7, compliment profile count: 1, compliment cute count: 2, compliment list count: 0, compliment note count: 20, compliment plain count: 47, compliment cool count: 20, compliment funny count: 20, compliment writer count: 12, compliment photos count: 2.'}

In [32]:
def cal_label(rating):
    return "Yes" if rating > threshold else "No"

In [33]:
# 使用 iterrows() 方法遍历每一行
for idx, row in inter_data.iterrows():
    ids = row['item_id']
    rs = row['rating:float']
    # print(ids,rs)
    # 每10个取一组
    g_len = max_length+1
    ids_arr = [ids[i:i+g_len] for i in range(0, len(ids), g_len)]
    rs_arr = [rs[i:i+g_len] for i in range(0, len(rs), g_len)]
    for id_arr,r_arr in zip(ids_arr,rs_arr):
        if len(id_arr) < 10:
            break
        his = id_arr[len(id_arr)-1]
        t_id = id_arr[len(id_arr)-1]

In [34]:
def build_item_infos(ids):
    item_infos = ''
    for i in ids:
        item_row = item_data[item_data["item_id"]==i].iloc[0]
        item_infos += item_temp1.replace('{item_name}',item_row["item_name:token_seq"]).replace('{item_id}',str(item_row["item_id"])).replace('{address_city_state}',f'{item_row["address:token_seq"]},{item_row["city:token_seq"]},{item_row["state:token"]}').replace('{zipcode}',item_row["postal_code:token"]).replace('{item_stars}',str(item_row["item_stars:float"])).replace('{item_review_count}',str(item_row["item_review_count:float"])).replace('{is_open}',str(item_row["is_open:float"])).replace('{category}',item_row["categories:token_seq"]).replace('{likes_count}',str(item_row['other']["likes_count"])).replace('{dislikes_count}',str(item_row['other']["dislikes_count"])).replace('{liking_rate}',str(item_row['other']["liking_rate"]))+'\n'
    return item_infos

def build_inter(row):
    user_row = user_data[user_data["user_id:token"]==row["user_id:token"]].iloc[0]
    user_info = user_temp1.replace('{user_id}',str(user_row["user_id"])).replace('{user_name}',str(user_row["user_name:token"])).replace('{fans_count}',str(user_row["fans:float"])).replace('{user_review_count}',str(user_row["user_review_count:float"])).replace('{user_useful_count}',str(user_row["user_useful:float"])).replace('{user_funny_count}',str(user_row["user_funny:float"])).replace('{average_stars}',str(user_row["average_stars:float"])).replace('{compliment_hot}',str(user_row["compliment_hot:float"])).replace('{compliment_more}',str(user_row["compliment_more:float"])).replace('{compliment_profile}',str(user_row["compliment_profile:float"])).replace('{compliment_cute}',str(user_row["compliment_cute:float"])).replace('{compliment_list}',str(user_row["compliment_list:float"])).replace('{compliment_note}',str(user_row["compliment_note:float"])).replace('{compliment_plain}',str(user_row["compliment_plain:float"])).replace('{compliment_cool}',str(user_row["compliment_cool:float"])).replace('{compliment_funny}',str(user_row["compliment_funny:float"])).replace('{compliment_writer}',str(user_row["compliment_writer:float"])).replace('{compliment_photos}',str(user_row["compliment_photos:float"]))

    user_inter = row['user_inter']
    p_id_groups = user_inter['p_id_groups']
    n_id_groups = user_inter['n_id_groups']
    for p_ids,n_ids in zip(p_id_groups,n_id_groups):
        # [0,1)根据0.6和0.4的比例进行线性转换
        if random.random() < 0.6:
            iid = p_ids.pop()
            flag = 'Yes'
        else:
            iid = n_ids.pop()
            flag = 'No'
        target_item_row = item_data[item_data["item_id"]==iid].iloc[0]
        target_movie = item_temp.replace('{item_name}',target_item_row["item_name:token_seq"]).replace('{item_id}',str(target_item_row["item_id"])).replace('{address_city_state}',f'{target_item_row["address:token_seq"]},{target_item_row["city:token_seq"]},{target_item_row["state:token"]}').replace('{zipcode}',target_item_row["postal_code:token"]).replace('{item_stars}',str(target_item_row["item_stars:float"])).replace('{item_review_count}',str(target_item_row["item_review_count:float"])).replace('{is_open}',str(target_item_row["is_open:float"])).replace('{category}',target_item_row["categories:token_seq"]).replace('{likes_count}',str(target_item_row['other']["likes_count"])).replace('{dislikes_count}',str(target_item_row['other']["dislikes_count"])).replace('{liking_rate}',str(target_item_row['other']["liking_rate"]))+'\n'

        user_temp_ = user_train_temp.replace('{user_info}', user_info).replace('{targe_item}',target_movie).replace('{likes_list}', build_item_infos(p_ids)).replace('{dislikes_list}', build_item_infos(n_ids)).replace('\n\n\n','\n\n')
        user_dict = {'instruction': user_temp_, 'input': '', 'output': flag}
        if random.random() < 0.8:
            ft_list.append(user_dict)
        else:
            pd_list.append(user_dict)

In [35]:
# 拼接信息
ft_list = [] # 微调
pd_list = [] # 预测
for idx, row in inter_data.iterrows():
    build_inter(row)

In [36]:
def export_json(data,export_path):
    df = pd.DataFrame(data)
    # 导出为格式化后的 JSON 文件
    df.to_json(export_path, orient='records')

In [37]:
export_json(item_data['info'].tolist()+user_data['info'].tolist(),w_pt_path)
export_json(ft_list,w_ft_path)
export_json(pd_list,w_pd_path)

In [38]:
# 读取 JSON 文件到 DataFrame
text_df = pd.read_json(w_pt_path)
text_df

                                                   text
0     item name: Gio Taco, address: 350 E Congress S...
1     item name: IndeBlue Modern Indian Food & Spiri...
2     item name: Truckee Bagel Company - Midtown, ad...
3     item name: Spice 28, address: 1228 Chestnut St...
4     item name: The Lemon Bar, address: 95 E Pine S...
...                                                 ...
6509  user name: Augustina, fans count: 3, user revi...
6510  user name: Pat, fans count: 5, user review cou...
6511  user name: Andrea, fans count: 67, user review...
6512  user name: Mike, fans count: 20, user review c...
6513  user name: Erica, fans count: 64, user review ...

[6514 rows x 1 columns]

In [39]:
# TALLRec

In [40]:
# 读取 JSON 文件到 DataFrame
train_data = pd.read_json(w_ft_path)
train_data

                                            instruction input output
0     You are a recommendation system that gives you...           No
1     You are a recommendation system that gives you...          Yes
2     You are a recommendation system that gives you...          Yes
3     You are a recommendation system that gives you...          Yes
4     You are a recommendation system that gives you...           No
...                                                 ...   ...    ...
4173  You are a recommendation system that gives you...           No
4174  You are a recommendation system that gives you...          Yes
4175  You are a recommendation system that gives you...          Yes
4176  You are a recommendation system that gives you...          Yes
4177  You are a recommendation system that gives you...           No

[4178 rows x 3 columns]

In [41]:
# 读取 JSON 文件到 DataFrame
test_data = pd.read_json(w_pd_path)
test_data

                                            instruction input output
0     You are a recommendation system that gives you...           No
1     You are a recommendation system that gives you...          Yes
2     You are a recommendation system that gives you...           No
3     You are a recommendation system that gives you...          Yes
4     You are a recommendation system that gives you...          Yes
...                                                 ...   ...    ...
1101  You are a recommendation system that gives you...          Yes
1102  You are a recommendation system that gives you...          Yes
1103  You are a recommendation system that gives you...          Yes
1104  You are a recommendation system that gives you...          Yes
1105  You are a recommendation system that gives you...          Yes

[1106 rows x 3 columns]

In [43]:
train_path = f"../../llm/{name}/train.json"
valid_path = f"../../llm/{name}/valid.json"
test_path = f"../../llm/{name}/test.json"

In [ ]:
tr_temp = {
    "instruction": "Given the user's preference and unpreference, identify whether the user will like the target item by answering \"Yes.\" or \"No.\".",
    "input": "User Preference: {user_preference}\nUser Unpreference: {user_preference}\nWhether the user will like the target item \"{target_item}\"?",
    "output": ""
}

In [ ]:
def build_tr_data(data):
    tr_list = []
    for index, s_row in data.iterrows():
        row = tr_temp.copy()
        row['output'] = s_row['output']
        instruction = s_row['instruction']
        # print(row)
        t_arr = instruction.split('\n')
        like_start = [index for index, value in enumerate(t_arr) if value == 'Likes List:'][0]
        dislike_start = [index for index, value in enumerate(t_arr) if value == 'Dislikes List:'][0]
        target_start = [index for index, value in enumerate(t_arr) if value == 'Target Item:'][0]
        like_list = []
        dislike_list = []
        for t in t_arr[like_start+1:dislike_start-1]:
            t = f"{t[t.index('item name:')+11:t.index(', address:')]} ({t[t.index('category: ')+10:len(t)-1]})"
            like_list.append(t)
        for t in t_arr[dislike_start+1:target_start-1]:
            t = f"{t[t.index('item name:')+11:t.index(', address:')]} ({t[t.index('category: ')+10:len(t)-1]})"
            dislike_list.append(t)
        t = t_arr[target_start+1]
        target_item = f"{t[t.index('item name:')+11:t.index(', address:')]} ({t[t.index('category: ')+10:t.index(', likes count')]})"
        like_str,dislike_str,target_strt = str(like_list).replace('[','').replace(']','').replace('\'','\"'),str(dislike_list).replace('[','').replace(']','').replace('\'','\"'),str(target_item).replace('[','').replace(']','').replace('\'','\"')
        row['input'] = row['input'].replace('{user_preference}',like_str).replace('{user_preference}',dislike_str).replace('{target_item}',target_strt)
        tr_list.append(row)
        # print(row)
    return tr_list

In [ ]:
tr_train_data = build_tr_data(train_data)
tr_test_data = build_tr_data(test_data)

l = int(len(tr_train_data)*6/8)
tr_valid_data = tr_train_data[l:]
tr_train_data = tr_train_data[:l]
tr_train_data,tr_valid_data,tr_test_data

In [ ]:
export_json(tr_train_data,train_path)
export_json(tr_valid_data,valid_path)
export_json(tr_test_data,test_path)